ALTER TABLE accounts 
ADD COLUMN term_days INTEGER DEFAULT 0,
ADD COLUMN can_replenish BOOLEAN DEFAULT false,
ADD COLUMN can_withdraw BOOLEAN DEFAULT false,
ADD COLUMN interest_rate INTEGER DEFAULT 0,
ADD COLUMN opened_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

ALTER TABLE requests
ADD COLUMN term_days INTEGER DEFAULT 0,
ADD COLUMN interest_rate INTEGER DEFAULT 0;

